import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const genres = [
  // Demografi & Pembaca Target
  'Shounen',
  'Seinen',
  'Shoujo',
  'Josei',
  'Kodomo',

  // Genre Utama & Fondasi
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Historical',
  'Horror',
  'Mystery',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'Slice of Life',
  'Supernatural',
  'Tragedy',
  'Thriller',
  'Crime',
  'Echi',

  // Setting & Lingkungan Hidup
  'School Life',
  'Workplace',
  'Family',
  'Medical',
  'Military',
  'Police',
  'Post-Apocalyptic',
  'Cyberpunk',
  'Steampunk',
  'Historical Drama',
  'Space',
  'Urban',
  'Rural',
  'College Life',
  'Office',
  'Hospital',
  'Prison',
  'Courtroom',
  'Royal Court',
  'Kingdom',
  'Empire',
  'Slums',
  'Wild West',
  'Desert',
  'Ocean',
  'Island',
  'Laboratory',
  'Asylum',
  'Subterranean',

  // Sub-Genre Khas Manhwa, Manhua & Manga
  'Isekai',
  'Reverse Isekai',
  'System',
  'Regression',
  'Reincarnation',
  'Cultivation',
  'Xianxia',
  'Xuanhuan',
  'Wuxia',
  'Murim',
  'Dungeon',
  'Tower',
  'Game',
  'LitRPG',
  'Otome Game',
  'Villainess',
  'Hunter',
  'Leveling',
  'Gate',
  'Transmigration',
  'Possession',
  'Virtual Reality',
  'MMORPG',
  'Tower Climbing',
  'Second Chance',
  'Returnee',
  'Summoned',
  'Rebirth',
  'Acrobatics',
  'Secret Identity',

  // Olahraga & Kompetisi
  'Sports',
  'Martial Arts',
  'Survival',
  'Superhero',
  'Mecha',
  'Delinquents',
  'Football',
  'Basketball',
  'Baseball',
  'Volleyball',
  'Tennis',
  'Boxing',
  'MMA',
  'Wrestling',
  'Swimming',
  'Track and Field',
  'Cycling',
  'Motorsport',
  'Golf',
  'E-Sports',
  'Chess',
  'Go',
  'Shogi',
  'Mahjong',
  'Card Games',
  'Gambling',
  'Archery',
  'Kendo',
  'Judo',
  'Karate',
  'Taekwondo',
  'Fencing',
  'Surfing',
  'Skateboarding',
  'Ice Skating',
  'Gymnastics',
  'Ping Pong',
  'Badminton',

  // Kulinari, Seni & Musik
  'Gourmet',
  'Cooking',
  'Food',
  'Baking',
  'Restaurant',
  'Bar',
  'Music',
  'Band',
  'Idol',
  'Singing',
  'Dance',
  'Art',
  'Painting',
  'Calligraphy',
  'Photography',
  'Fashion',
  'Acting',
  'Theatre',
  'Filmmaking',
  'Crafting',

  // Fantasi, Ilmu Gaib & Makhluk Halus
  'Magic',
  'Vampire',
  'Zombies',
  'Demons',
  'Monsters',
  'Time Travel',
  'Aliens',
  'Angels',
  'Ghosts',
  'Yokai',
  'Mythology',
  'Dragons',
  'Elves',
  'Orcs',
  'Dwarves',
  'Necromancy',
  'Alchemy',
  'Witchcraft',
  'Shamanism',
  'Exorcism',
  'Curse',
  'Shape Shifter',
  'Werewolf',
  'Mermaid',
  'Gods',
  'Deities',
  'Beastmen',

  // Romansa & Hubungan
  'Harem',
  'Reverse Harem',
  'Love Triangle',
  'Boys Love',
  'Girls Love',
  'Shounen Ai',
  'Shoujo Ai',
  'Yaoi',
  'Yuri',
  'Arranged Marriage',
  'Contract Marriage',
  'Fake Relationship',
  'Co-habitation',
  'Childhood Friends',
  'Enemies to Lovers',
  'Age Gap',
  'Office Romance',
  'Unrequited Love',
  'First Love',
  'Forbidden Love',
  'Polyamory',
  'Fluff',
  'Teasing',

  // Kehidupan & Profesi
  'Business',
  'Finance',
  'Politics',
  'Trading',
  'Farming',
  'Building',
  'Management',
  'Kingdom Building',
  'Teacher',
  'Student',
  'Doctor',
  'Nurse',
  'Lawyer',
  'Detective',
  'Spy',
  'Assassin',
  'Mercenary',
  'Knight',
  'Ninja',
  'Samurai',
  'Pirate',
  'Thief',
  'Hunter Guild',
  'Adventurer',
  'Chef',
  'Craftsman',
  'Blacksmith',
  'Tailor',

  // Psikologi, Gelap & Konflik
  'Gore',
  'Bloody',
  'Violence',
  'Revenge',
  'Betrayal',
  'Dark Fantasy',
  'Survival Horror',
  'Psychological Horror',
  'Mind Games',
  'Monsters Inside',
  'Insanity',
  'Dystopia',
  'Apocalypse',
  'Disaster',
  'War',
  'Strategy',
  'Tactics',
  'Corruption',
  'Conspiracy',
  'Cult',
  'Kidnapping',
  'Hostage',
  'Terrorism',

  // Kategori Tambahan & Tema Unik
  'Philosophical',
  'Parody',
  'Satire',
  'Slapstick',
  'Monster Girls',
  'Crossdressing',
  'Gender Bender',
  'Body Swap',
  'Gag',
  '4-Koma',
  'Short Stories',
  'Anthology',
  'Webtoon',
  'Full Color',
  'CGI',
  'Showbiz',
  'Streaming',
  'Vtubers',
  'Social Media',
  'Hacking',
  'Robots',
  'Androids',
  'Artificial Intelligence',
  'Clones',
  'Genetics',
  'Mutants',
  'Superpowers',
  'Espers',
  'Telekinesis',
  'Time Loop',
  'Parallel World',
  'Multiverse',
  'Dungeon Core',
  'Monster Evolution',
  'Pet Companion',
  'Raising Children',
  'Parenthood',
  'Cute Girls Doing Cute Things',
  'Cute Boys Doing Cute Things',
  'Camping',
  'Fishing',
  'Travel',
  'Tourism',
  'Hot Springs',
  'Spa',
  'Video Games',
  'Board Games',
  'Escape Room',
  'Treasure Hunt',
  'Archaeology',
  'Antiques',
  'Museum',
  'Astronomy',
  'Aviation',
  'Nautical',
  'Train',
  'Automobile',
  'Bikes',
  'Animal Companions',
  'Cats',
  'Dogs',
  'Boutique',
  'Hotel Management',
  'Tavern',
  'Alchemy Shop',
  'Magic Academy',
  'Hero Party',
  'Demon King',
  'Hero vs Demon King',
  'False Hero',
  'S-Rank',
  'F-Rank to S-Rank',
  'Overpowered Main Character',
  'Weak to Strong',
  'Smart Main Character',
  'Anti-Hero',
  'Villain Main Character',
  'Non-Human Main Character'
]

async function main() {
  console.log('Starting genre seed...')

  for (const name of genres) {
    const slug = name
      .toLowerCase()
      .replace(/&/g, 'and')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')

    await prisma.genre.upsert({
      where: {
        slug,
      },
      update: {
        name,
      },
      create: {
        name,
        slug,
      },
    })
  }

  console.log(`Successfully seeded ${genres.length} genres.`)
}

main()
  .catch((error) => {
    console.error('Genre seed failed:', error)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
