name: Ellaria Database Push

on:
  workflow_dispatch:

jobs:
  database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Prisma Generate
        run: npx prisma generate

      - name: Prisma DB Push
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
